#pragma once

#include <cstddef>

#include "airbrake/apogee_predictor.hpp"
#include "airbrake/atmosphere.hpp"
#include "airbrake/drag_table.hpp"
#include "airbrake/flight_sample.hpp"
#include "airbrake/simulation_config.hpp"

namespace airbrake {

// Describes the result of a deployment-controller update
enum class ControllerStatus {
    commanded,
    inactive, 
    prediction_unavailable,
    invalid_input
};

// Contains the deployment command and prediction generated by the controller
struct DeploymentCommand {
    double deployment_fraction;
    PredictionResult prediction;
    ControllerStatus status;
};

// Selects an airbrake deployment level based on the current flight state and predicted apogee
class DeploymentController {
public:
/**
    Creates a deployment controller

    @param config Simulation and vehicle configuration.
    @param drag_table Aerodynamic CdA lookup table.
    @param max_mach Maximum Mach number at which deployment is allowed.
    @param deployment_levels Number of discrete deployment commands, including 0% and 100%.
*/
    DeploymentController(
        SimulationConfig config,
        DragTable drag_table,
        double max_mach = 0.7,
        std::size_t deployment_levels = 11 // 11 = 10% increment. 21 = 5% increment
    );

    /**
        Calculates the deployment command for the current flight state.

        The controller evaluates predicted apogees at available deployment
        levels and returns the selected command and its prediction.

        @param state Current normalized vertical flight state.
        @return DeploymentCommand (Deployment command, predicted apogee, and controller status.)
    */
    DeploymentCommand compute(
        const VerticalState& state
    ) const;

private:
    SimulationConfig config_;
    Atmosphere atmosphere_;
    ApogeePredictor predictor_;
    double max_mach_;
    std::size_t deployment_levels_;
};

}